import test from 'node:test';
import assert from 'node:assert/strict';
import { newState, propose, apply, undoLast, validateProject, validateState, proposedProject, diff } from '../dist/assets/model.js';
import { escapeHTML } from '../dist/assets/ui.js';
const prompt = 'Подготовь запуск за 4 недели, бюджет до 60 000 ₴.';
test('proposal does not mutate persisted project',()=>{ const s=newState(); const p=propose(s,prompt); assert.equal(s.project.budget,45000); assert.equal(p.changes.length,3); });
test('intent chooses a bounded component catalog',()=>{ assert.deepEqual(propose(newState(),'Разбери бюджет до 60000 ₴.').modules,['budget','brief']); assert.deepEqual(propose(newState(),'Фокус').modules,['roadmap']); });
test('only approved fields are committed',()=>{ const s=newState(); const p=propose(s,prompt); const n=apply(s,p,['budget']); assert.equal(n.project.budget,60000); assert.equal(n.project.weeks,6); assert.equal(n.project.stage,'idea'); });
test('undo restores data while retaining audit trail',()=>{ const s=newState(); const p=propose(s,prompt); const n=apply(s,p,['budget','weeks','stage']); const u=undoLast(n); assert.deepEqual(u.project,s.project); assert.equal(u.history.length,2); assert.equal(u.history[1].kind,'undo'); assert.equal(u.revision,2); });
test('stale proposals are rejected',()=>{ const s=newState(); const p=propose(s,prompt); const n=apply(s,p,['budget']); assert.throws(()=>apply(n,p,['weeks']),/изменился/); });
test('empty approval is not a mutation',()=>{ const s=newState(); assert.throws(()=>apply(s,propose(s,prompt),[]),/Нет выбранных/); });
test('unknown intent does not pretend to understand',()=>assert.throws(()=>propose(newState(),'Спой про чёрную дыру'),/Не удалось/));
test('out-of-bounds amounts and durations rejected',()=>{ assert.throws(()=>propose(newState(),'Запуск за 99 недель, бюджет до 1000 ₴.')); assert.throws(()=>propose(newState(),'Бюджет до 999999 ₴.')); });
test('unsupported currency is not silently converted',()=>assert.throws(()=>propose(newState(),'План за 4 недели, бюджет 60000 рублей'),/гривны/));
test('malicious extra fields and prototype keys rejected',()=>{ assert.equal(validateProject({...newState().project,html:'<script>'}),false); assert.equal(validateProject(JSON.parse('{"__proto__":{},"title":"test","budget":60000,"weeks":4,"stage":"idea","done":[false,false,false,false]}')),false); });
test('HTML payload in text is escaped, not executed',()=>assert.equal(escapeHTML('<img src=x onerror="alert(1)">'),'&lt;img src=x onerror=&quot;alert(1)&quot;&gt;'));
test('invalid state revision and history are rejected',()=>{ assert.equal(validateState({...newState(),revision:-1}),false); assert.equal(validateState({...newState(),history:[{}]}),false); assert.equal(validateState(newState()),true); });
test('preview respects unchecked differences',()=>{ const s=newState(); const p=propose(s,prompt); assert.deepEqual(proposedProject(s,p,[]),s.project); });
test('history and undo have bounded growth',()=>{ let s=newState(); for(let i=0;i<55;i++){const p=propose(s,`Бюджет до ${60000+i} ₴.`); s=apply(s,p,['budget']);} assert.equal(s.history.length,40); assert.equal(s.undo.length,20); });
test('changes have a validated target',()=>assert.throws(()=>diff(newState().project,{...newState().project,budget:NaN})));
test('overlong prompts rejected',()=>assert.throws(()=>propose(newState(),'План '+ 'a'.repeat(501)),/500/));
