import { money, type Project, type ModuleKind } from './model.js';
import { escapeHTML as esc, icon } from './ui.js';
export const taskNames = ['Замысел и права', 'Текст и редактура', 'Дизайн и сборка', 'Проверка и выпуск'];
const taskDescriptions = ['Уточнить аудиторию, объём и разрешения', 'Редактура, терминология, независимая проверка', 'Обложка, вёрстка, доступные форматы', 'Проверка файлов и решение о публикации'];
export function renderModule(kind: ModuleKind, p: Project): string {
  if (kind === 'roadmap') return `<section class="module roadmap" aria-labelledby="roadmap-title"><div class="module-heading"><span class="module-index">01 / ПЛАН</span><span>${p.weeks} недели · шаблон</span></div><h2 id="roadmap-title">От замысла<br>до первого читателя.</h2><div class="task-list">${taskNames.map((name, i) => `<div class="task-row ${p.done[i] ? 'is-done' : ''}"><button class="task-check" type="button" data-task="${i}" aria-label="${p.done[i] ? 'Вернуть в работу' : 'Отметить готовность'}: ${name}" aria-pressed="${p.done[i]}">${p.done[i] ? icon('check', 16) : `<span>0${i + 1}</span>`}</button><div><h3>${name}</h3><p>${taskDescriptions[i]}</p></div><span class="week-label">${Math.max(1, Math.ceil((i + 1) * p.weeks / 4))} нед.</span></div>`).join('')}</div><div class="module-foot">${icon('clock', 15)} Это равномерный шаблон этапов, не оценка трудозатрат.</div></section>`;
  if (kind === 'budget') {
    const ratios = [.42, .28, .18, .12]; const names = ['Редактура', 'Дизайн', 'Проверка', 'Резерв'];
    return `<section class="module budget" aria-labelledby="budget-title"><div class="module-heading"><span class="module-index">02 / РЕСУРСЫ</span>${icon('sliders')}</div><h2 id="budget-title">Бюджет под контролем.</h2><div class="budget-total">${money(p.budget)}</div><p class="budget-caption">Лимит проекта · гривны</p><div class="allocation" aria-label="Доли бюджета: 42, 28, 18 и 12 процентов">${ratios.map((r, i) => `<span class="allocation-${i}" style="flex:${r}"></span>`).join('')}</div><div class="budget-lines">${names.map((n, i) => `<div><span><i class="swatch allocation-${i}"></i>${n}</span><strong>${money(Math.round(p.budget * ratios[i]!))}</strong></div>`).join('')}</div><button type="button" class="budget-edit" data-manual>${icon('sliders', 15)} Изменить вручную ${icon('arrow', 15)}</button><p class="budget-disclaimer">Учебные пропорции, не рыночные ставки.</p></section>`;
  }
  return `<section class="module brief" aria-labelledby="brief-title"><div>${icon('shield', 20)}</div><div><h2 id="brief-title">Не делать за вашей спиной.</h2><p>Публикация, платежи и внешняя отправка не подключены. Название «${esc(p.title)}» и все цифры — учебный проект.</p><button class="text-button" type="button" data-source="agency">Почему контроль — часть UX ${icon('external', 14)}</button></div></section>`;
}
